export const CREATE_LEADERBOARD = 'CREATE_LEADERBOARD';
export const DELETE_LEADERBOARD = 'DELETE_LEADERBOARD';
export const FETCH_LEADERBOARD = 'FETCH_LEADERBOARD';
export const AUTHORIZE_USER = 'AUTHORIZE_USER';
export const LEADERBOARD_ERROR = 'CREATE_LEADERBOARD_ERROR';
