export const CREATE_LEADERBOARD = 'CREATE_LEADERBOARD';
export const DELETE_LEADERBOARD = 'DELETE_LEADERBOARD';
export const CLEAR_LEADERBOARD = 'CLEAR_LEADERBOARD';
export const UNSET_LEADERBOARD = 'UNSET_LEADERBOARD';
export const FETCH_LEADERBOARD = 'FETCH_LEADERBOARD';
export const LOADING_LEADERBOARD = 'LOADING_LEADERBOARD';
export const LEADERBOARD_ERROR = 'CREATE_LEADERBOARD_ERROR';
